### ISSUE TITLE
Crash with Burnt mod

### ISSUE THREAD

**Issue by RenClayd** [TeamGalena/oreganized#44]
---- Minecraft Crash Report ----

Time: 2024-07-26 16:52:42
Description: Initializing game

net.minecraftforge.fml.ModLoadingException: Burnt 1.7.2 (burnt) encountered an error during the common_setup event phase
§7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.20.1-47.2.20.jar%23342!/:?] {}

**Comment by Leawind** [comment]
Just passing by...

If you put the log in a code block like this

```log
---- Minecraft Crash Report ----

Time: 2024-07-26 16:52:42
Description: Initializing game

net.minecraftforge.fml.ModLoadingException: Burnt 1.7.2 (burnt) encountered an error during the common_setup event phase
§7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.20.1-47.2.20.jar%23342!/:?] {}
```

It might be easier to read.

**Comment by hedkne43rei0pow** [comment]
burt is made in mccreator. so that probably doesnt help

**Comment by KreloX** [comment]
Can't reproduce, you also didn't post the full log
