### ISSUE TITLE
Using an Electrum weapon on another player causes a crash

### ISSUE THREAD

**Issue by Carmenboy1** [TeamGalena/oreganized#71]
### What happened?

I was playing on a private smp with a friend when i went to wack him with my electrum sword (cause he was being CRINGE) and it crashed the game. i also tested this with my electrum axe and the same thing happened

### Mod Version

3.1.2

### Minecraft Version

1.20

### Relevant log output

```Shell
Time: 2024-11-29 07:46:21
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_6846_()" because the return value of "net.minecraftforge.network.PacketDistributor.getServer()" is null
	at net.minecraftforge.network.PacketDistributor.lambda$playerListPointConsumer$5(PacketDistributor.java:220) ~[forge-1.20.1-47.3.11-universal.jar%23495!/:?] {re:mixin,re:classloading,pl:mixin:APP:moonlight.mixins.json:PacketDistributorHackMixin,pl:mixin:A}
	at net.minecraftforge.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:165) ~[forge-1.20.1-47.3.11-universal.jar%23495!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.20.1-47.3.11-universal.jar%23495!/:?] {re:mixin,re:classloading}
	at galena.oreganized.world.KineticDamage.apply(KineticDamage.java:39) ~[%5BCONTENT%5D%20Oreganized%201.20.1-3.1.2.jar%23358!/:3.1.2] {re:mixin,re:classloading}
	at net.minecraft.world.item.enchantment.EnchantmentHelper.handler$ega000$applyKineticDamage(EnchantmentHelper.java:1517) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,re:classloading,pl:mixin:APP:allurement.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:caverns_and_chasms.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:oreganized.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:quark.mixins.json:EnchantmentHelperMixin,pl:mixin:A}
	at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44896_(EnchantmentHelper.java) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,re:classloading,pl:mixin:APP:allurement.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:caverns_and_chasms.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:oreganized.mixins.json:EnchantmentHelperMixin,pl:mixin:APP:quark.mixins.json:EnchantmentHelperMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_5706_(Player.java:1195) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:exposure-common.mixins.json:PlayerMixin,pl:mixin:APP:notenoughanimations.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinPlayerEntity,pl:mixin:APP:netherexp-common.mixins.json:entity.PlayerMixin,pl:mixin:APP:species.mixins.json:PlayerMixin,pl:mixin:APP:combatnouveau.common.mixins.json:PlayerMixin,pl:mixin:APP:combatnouveau.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:environmental.mixins.json:PlayerMixin,pl:mixin:APP:allurement.mixins.json:PlayerMixin,pl:mixin:APP:caverns_and_chasms.mixins.json:PlayerMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.world.entity.player.PlayerVRMixin,pl:mixin:APP:alexscaves.mixins.json:PlayerMixin,pl:mixin:APP:oreganized.mixins.json:PlayerMixin,pl:mixin:APP:sounds.mixins.json:ui.PlayerEntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:etcetera.mixins.json:PlayerEntityMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.crawling.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.trident_enchantments.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.exp_drop.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.repelling_void.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.hunger_is.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.despawning_items_blink.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.canhit.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:a_fixes.use_player_list_name_in_tag.MixinPlayerEntity,pl:mixin:APP:fabrication.mixins.json:a_fixes.adventure_tags_in_survival.MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105223_(MultiPlayerGameMode.java:396) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_202354_(Minecraft.java:1626) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:exposure-common.mixins.json:MinecraftMixin,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.MinecraftVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeMinecraftVRMixin,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin,pl:mixin:APP:sounds.mixins.json:ui.ScreenSoundEffect,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin,pl:mixin:APP:yacl.mixins.json:MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:APP:vivecraftcompat.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1972) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:exposure-common.mixins.json:MinecraftMixin,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.MinecraftVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeMinecraftVRMixin,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin,pl:mixin:APP:sounds.mixins.json:ui.ScreenSoundEffect,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin,pl:mixin:APP:yacl.mixins.json:MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:APP:vivecraftcompat.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:exposure-common.mixins.json:MinecraftMixin,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.MinecraftVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeMinecraftVRMixin,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin,pl:mixin:APP:sounds.mixins.json:ui.ScreenSoundEffect,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin,pl:mixin:APP:yacl.mixins.json:MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:APP:vivecraftcompat.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:exposure-common.mixins.json:MinecraftMixin,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.MinecraftVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeMinecraftVRMixin,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin,pl:mixin:APP:sounds.mixins.json:ui.ScreenSoundEffect,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin,pl:mixin:APP:yacl.mixins.json:MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:APP:vivecraftcompat.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23490!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:exposure-common.mixins.json:MinecraftMixin,pl:mixin:APP:polytone-common.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:combatnouveau.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:vivecraft.mixins.json:client_vr.MinecraftVRMixin,pl:mixin:APP:vivecraft.forge.mixins.json:ForgeMinecraftVRMixin,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin,pl:mixin:APP:sounds.mixins.json:ui.ScreenSoundEffect,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin,pl:mixin:APP:yacl.mixins.json:MinecraftMixin,pl:mixin:APP:sound_physics_remastered.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:APP:vivecraftcompat.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-47.3.11.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cubes-without-borders.mixins.json:MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:APP:vivecraft.mixins.json:client.main.MainMixin,pl:mixin:APP:screenshotclipboard-common.mixins.json:AWTHackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by Carmenboy1** [comment]
(incase that isnt enough i made a link to the log for further examination: https://mclo.gs/sUpsmJe)

**Comment by thelegitdolt** [comment]
i was NOT being cringe liar
